version: '3.8'

services:
  # API Gateway
  nginx-gateway:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"  # For HTTPS
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - product-service
      - order-service
      - inventory-service
      - user-service
    networks:
      - microservice-network

  # Product Service and its database
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - INVENTORY_SERVICE_URL=http://inventory-service:8002/api/v1
      - KAFKA_BROKER=automq:9092
    env_file:
      - ./product-service/.env
    depends_on:
      - mongodb-product
      - automq
    networks:
      - microservice-network

  mongodb-product:
    image: mongo:5.0
    volumes:
      - mongodb_product_data:/data/db
    networks:
      - microservice-network
    environment:
      - MONGO_INITDB_DATABASE=product_db

  # Order Service and its database
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - USER_SERVICE_URL=http://user-service:8003/api/v1
      - PRODUCT_SERVICE_URL=http://product-service:8000/api/v1
      - INVENTORY_SERVICE_URL=http://inventory-service:8002/api/v1
      - KAFKA_BROKER=automq:9092
    env_file:
      - ./order-service/.env
    depends_on:
      - mongodb-order
      - automq
    networks:
      - microservice-network

  mongodb-order:
    image: mongo:5.0
    volumes:
      - mongodb_order_data:/data/db
    networks:
      - microservice-network
    environment:
      - MONGO_INITDB_DATABASE=order_db

  # Inventory Service and its database
  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - PRODUCT_SERVICE_URL=http://product-service:8000/api/v1
      - DATABASE_URL=postgresql://postgres:postgres@postgres-inventory:5432/inventory_db
      - KAFKA_BROKER=automq:9092
    env_file:
      - ./inventory-service/.env
    depends_on:
      - postgres-inventory
      - automq
    networks:
      - microservice-network

  postgres-inventory:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventory_db
    volumes:
      - postgres_inventory_data:/var/lib/postgresql/data
    networks:
      - microservice-network

  # User Service and its database
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-user:5432/user_db
      - KAFKA_BROKER=automq:9092
    env_file:
      - ./user-service/.env
    depends_on:
      - postgres-user
      - automq
    networks:
      - microservice-network

  postgres-user:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_db
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    networks:
      - microservice-network

  # Kafka Service (AutoMQ)
  automq:
    image: automq/automq-ce:latest
    ports:
      - "9092:9092"
      - "8080:8080"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://automq:9092
      KAFKA_LOG_DIRS: /kafka-logs
    volumes:
      - automq_data:/kafka-logs
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge

volumes:
  mongodb_product_data:
  mongodb_order_data:
  postgres_inventory_data:
  postgres_user_data:
  automq_data:
