services:
  inventory-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - microservice-network
    environment:
      - PRODUCT_SERVICE_URL=http://product-service:8000/api/v1
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/inventory_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8002/health || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventory_db
    networks:
      - microservice-network
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  microservice-network:
    external: true

volumes:
  postgres_data: